# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fac560ebb579d4174dcadfecb5c94dcb119b66c6bc6249c442aefc3771a38b6b9495ad887bef122cd56387fc583e213571d855682ec3a58f32970a78d0f32f9

test:
  secret_key_base: fa19c3ad4eb764ee88a04fe341153620098e76f368c9385aa8b583ddfa62cd745ce17db1cd4731f5f67119aa59d7227d0c6bedd2f286abb1c7f20ee5119a6165

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
